[02-26-2021 11:35:40] 	 Making Discord :can only concatenate str (not "NoneType") to str 
[02-26-2021 11:35:40] 	 local variable 'embed' referenced before assignment:new 
[03-26-2021 23:48:12] 	 500 Server Error: Internal Server Error for url: https://discordapp.com/api/webhooks/637129714439553024/EqFU8c9st6dDY_rTLWAIwsJpOrE3LGgL4YXiLZopPUsqboFNZTGjJSS2bNsMAcsdaljL:keyword 
[03-26-2021 23:50:15] 	 500 Server Error: Internal Server Error for url: https://discordapp.com/api/webhooks/622136934956924990/-FQO3tUSe_z5BCNokAaoDIfP0QTvMeJZorSyAjA9Xs09PsvpQvHjqFCy_3KK5mJtmNBH:sale 
[09-08-2021 15:04:40] 	 502 Server Error: Bad Gateway for url: https://discordapp.com/api/webhooks/637130395137212437/loBLm9N3e2S9K8q5zEb15j6uZk-8iocsBhREkE4yJM8wlLxfwhpSI0C7LpPP6xniCd97:new 
[10-05-2021 19:18:20] 	 500 Server Error: Internal Server Error for url: https://discordapp.com/api/webhooks/637129714439553024/EqFU8c9st6dDY_rTLWAIwsJpOrE3LGgL4YXiLZopPUsqboFNZTGjJSS2bNsMAcsdaljL:keyword 
[11-15-2021 16:01:04] 	 HTTPSConnectionPool(host='discordapp.com', port=443): Max retries exceeded with url: /api/webhooks/637129714439553024/EqFU8c9st6dDY_rTLWAIwsJpOrE3LGgL4YXiLZopPUsqboFNZTGjJSS2bNsMAcsdaljL (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f59267e2430>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')):keyword 
[11-15-2021 17:07:38] 	 HTTPSConnectionPool(host='discordapp.com', port=443): Max retries exceeded with url: /api/webhooks/637129714439553024/EqFU8c9st6dDY_rTLWAIwsJpOrE3LGgL4YXiLZopPUsqboFNZTGjJSS2bNsMAcsdaljL (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f59243fcc70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')):keyword 
[11-15-2021 19:17:35] 	 HTTPSConnectionPool(host='discordapp.com', port=443): Max retries exceeded with url: /api/webhooks/637129714439553024/EqFU8c9st6dDY_rTLWAIwsJpOrE3LGgL4YXiLZopPUsqboFNZTGjJSS2bNsMAcsdaljL (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5925f9d6d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')):keyword 
[11-16-2021 18:52:39] 	 404 Client Error: Not Found for url: https://discordapp.com/api/webhooks/637129714439553024/EqFU8c9st6dDY_rTLWAIwsJpOrE3LGgL4YXiLZopPUsqboFNZTGjJSS2bNsMAcsdaljL:keyword 
[11-19-2021 05:21:41] 	 HTTPSConnectionPool(host='discordapp.com', port=443): Max retries exceeded with url: /api/webhooks/637129714439553024/EqFU8c9st6dDY_rTLWAIwsJpOrE3LGgL4YXiLZopPUsqboFNZTGjJSS2bNsMAcsdaljL (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5934114670>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')):keyword 
[11-19-2021 05:22:26] 	 HTTPSConnectionPool(host='discordapp.com', port=443): Max retries exceeded with url: /api/webhooks/637129714439553024/EqFU8c9st6dDY_rTLWAIwsJpOrE3LGgL4YXiLZopPUsqboFNZTGjJSS2bNsMAcsdaljL (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f590fd7aaf0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')):keyword 
[11-19-2021 05:23:06] 	 HTTPSConnectionPool(host='discordapp.com', port=443): Max retries exceeded with url: /api/webhooks/637129714439553024/EqFU8c9st6dDY_rTLWAIwsJpOrE3LGgL4YXiLZopPUsqboFNZTGjJSS2bNsMAcsdaljL (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f59266169d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')):keyword 
[11-19-2021 05:25:46] 	 HTTPSConnectionPool(host='discordapp.com', port=443): Max retries exceeded with url: /api/webhooks/637129714439553024/EqFU8c9st6dDY_rTLWAIwsJpOrE3LGgL4YXiLZopPUsqboFNZTGjJSS2bNsMAcsdaljL (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f59265912e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')):keyword 
[11-19-2021 05:26:09] 	 HTTPSConnectionPool(host='discordapp.com', port=443): Max retries exceeded with url: /api/webhooks/637129714439553024/EqFU8c9st6dDY_rTLWAIwsJpOrE3LGgL4YXiLZopPUsqboFNZTGjJSS2bNsMAcsdaljL (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f592405fc10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')):keyword 
[11-19-2021 05:26:32] 	 HTTPSConnectionPool(host='discordapp.com', port=443): Max retries exceeded with url: /api/webhooks/637129714439553024/EqFU8c9st6dDY_rTLWAIwsJpOrE3LGgL4YXiLZopPUsqboFNZTGjJSS2bNsMAcsdaljL (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5924222280>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')):keyword 
[11-19-2021 05:28:55] 	 HTTPSConnectionPool(host='discordapp.com', port=443): Max retries exceeded with url: /api/webhooks/637129714439553024/EqFU8c9st6dDY_rTLWAIwsJpOrE3LGgL4YXiLZopPUsqboFNZTGjJSS2bNsMAcsdaljL (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f59266e4490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')):keyword 
[11-19-2021 05:29:26] 	 HTTPSConnectionPool(host='discordapp.com', port=443): Max retries exceeded with url: /api/webhooks/637129714439553024/EqFU8c9st6dDY_rTLWAIwsJpOrE3LGgL4YXiLZopPUsqboFNZTGjJSS2bNsMAcsdaljL (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f592640fb50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')):keyword 
[11-19-2021 05:29:47] 	 HTTPSConnectionPool(host='discordapp.com', port=443): Max retries exceeded with url: /api/webhooks/637129714439553024/EqFU8c9st6dDY_rTLWAIwsJpOrE3LGgL4YXiLZopPUsqboFNZTGjJSS2bNsMAcsdaljL (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f590ff73a00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')):keyword 
[11-19-2021 05:30:15] 	 HTTPSConnectionPool(host='discordapp.com', port=443): Max retries exceeded with url: /api/webhooks/637129714439553024/EqFU8c9st6dDY_rTLWAIwsJpOrE3LGgL4YXiLZopPUsqboFNZTGjJSS2bNsMAcsdaljL (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f59267e2940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')):keyword 
[11-19-2021 05:42:47] 	 HTTPSConnectionPool(host='discordapp.com', port=443): Max retries exceeded with url: /api/webhooks/622136934956924990/-FQO3tUSe_z5BCNokAaoDIfP0QTvMeJZorSyAjA9Xs09PsvpQvHjqFCy_3KK5mJtmNBH (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f592638c160>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')):sale 
[11-19-2021 05:45:08] 	 HTTPSConnectionPool(host='discordapp.com', port=443): Max retries exceeded with url: /api/webhooks/622136934956924990/-FQO3tUSe_z5BCNokAaoDIfP0QTvMeJZorSyAjA9Xs09PsvpQvHjqFCy_3KK5mJtmNBH (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f590fabd310>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')):sale 
